INSERT INTO skills (name) VALUES
                              ('Java'),
                              ('Spring Boot'),
                              ('JavaScript'),
                              ('TypeScript'),
                              ('React'),
                              ('Next.js'),
                              ('Node.js'),
                              ('Go'),
                              ('Python'),
                              ('Docker'),
                              ('Kubernetes'),
                              ('AWS'),
                              ('SQL'),
                              ('PostgreSQL'),
                              ('MongoDB'),
                              ('Git'),
                              ('REST APIs'),
                              ('Microservices'),
                              ('Linux'),
                              ('CI/CD');